### ISSUE TITLE
Changes in import process

### ISSUE THREAD

**Issue by m-montesdeoca** [BinPar/Satcom-SMD#2]
- [x] Translate the texts "Seleccionar archivo - Nada seleccionado".
- [x] Remove the \* after the fields captions (assuming it is useless).
- [x] Include a field to select the _Biller entity_ (currently only SMD). The _Biller entities_ table, anyway, must be manageable through an option in the _Manage tables_ menu.
- [x] Immediately after launching the import process, the system will proceed as follows:
- If MobNo field matches an existing number, OK (current behaviour).
- If MobNo does not match any existing number, show a grid with the following columns **(DISTINCT values):**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-InvNo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-MobNo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-InvRef (**NON-DISTINCT value**; i.e.: if we find distinct values for this field, the grid must show only the **first** of them (excluding possible blank values). Typically, we may find this situation in some cases in which the same MobNo has different values in the traffic file and in the non-traffic file)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Combos to select (option to add a new record, redirecting to the corresponding vessel/terminal form)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Vessel
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Terminal
- Option to run the process again
- Once the process is finished, the resulting record should be named after the month (in mm-yyyy format) +  InvNo (not “Inmarsat").

[6061886186-Traffic File.traffic.xlsx](https://github.com/BinPar/Satcom-SMD/files/543957/6061886186-Traffic.File.traffic.xlsx): Raw CSV saved as Excel file.
[6061886186-Traffic File.xlsx](https://github.com/BinPar/Satcom-SMD/files/543958/6061886186-Traffic.File.xlsx): Excel file after being processed by the user manually.
[6061886186-Traffic File.pdf](https://github.com/BinPar/Satcom-SMD/files/543956/6061886186-Traffic.File.pdf): Processed Excel file saved as PDF, ready to be sent to the customer.

**Comment by NicoBinpar** [comment]
The biller entity (Entidad facturadora en SatcomMagic) is asociated to a vessel. It will the same for SMD.

**Comment by NicoBinpar** [comment]
En el proceso de Importación sólo queda pendiente asociar la entidad facturadora al periodo de facturación.

![image](https://cloud.githubusercontent.com/assets/17255501/20441070/1f94cd5c-adc3-11e6-9dad-f55870624685.png)
