### ISSUE TITLE
Non-traffic files import

### ISSUE THREAD

**Issue by m-montesdeoca** [BinPar/Satcom-SMD#4]
Basically, the same rules that we find in the traffic files apply to the non-traffic files: the final price is obtained by applying to the _TotChg_ field the same rate of exchange and margin that in the traffic file. The fields in the file and the columns in the final CDR are somehow different, but the process is essentially the same, as it can be deducted from the following files attached:
- Raw non-traffic file in original text format: [50184.78738.6071903087.20160731.zip](https://github.com/BinPar/Satcom-SMD/files/544627/50184.78738.6071903087.20160731.zip)
- Raw non-traffic file converted to Excel, showing how the rate of exchange and the margin are applied in order to get the final price in ZAR for the vessel “I do”: [50184.78738.6071903087.20160731.non_traf.xlsx](https://github.com/BinPar/Satcom-SMD/files/544628/50184.78738.6071903087.20160731.non_traf.xlsx)
- Final CDR PDF for the vessel “I do”: [I do - non traffic - august.pdf](https://github.com/BinPar/Satcom-SMD/files/544629/I.do.-.non.traffic.-.august.pdf)

**Comment by NicoBinpar** [comment]
The creation of PDFs will be done in issue #5
